### ISSUE TITLE
zip-file needs to be renamed before Factorio can load the mod

### ISSUE THREAD

**Issue by weep** [Suprcheese/Logistics-Railway#4]
If you're like me and don't want to unzip the files to the mod folder and just keep the compressed archive, the archive needs to be renamed in order for Factorio to load it.

The mod is named "Logistics Railway" in "info.json" but GitHub replaces the "Logistics Railway_<ver>.zip" to "Logistics.Railway_<ver>.zip". Therefor the we get this error:

```
---------------------------
Error
---------------------------
Filename of mod %appdata%\Factorio\mods\Logistics.Railway_1.0.6.zip doesn't match the expected Logistics Railway_1.0.6.zip (case sensitive!)
---------------------------
OK   
---------------------------
```

Renaming the archive to include the space allows Factorio to load the mod. 

I would suggest renaming the mod to either "Logistics-Railway" (since this is the name on GitHub), "Logistics.Railway" or just "LogisticsRailway".
But we're already seeing it being referenced as "dependencies" in other mods like https://github.com/Choumiko/TheFatController/commit/274733c0645cc2cb0989d44868c9775d6ac8fd29

**Comment by Suprcheese** [comment]
Eh, the Github releases page is not where I expect users to primarily download from. Rather, the Forum thread and its attachment (https://forums.factorio.com/viewtopic.php?f=93&t=21462) are -- and, in the future, the integrated Mod Portal will surely be the primary official download location.

**Comment by weep** [comment]
True, but building a script which utilizes the GitHub API to get the latest version of a mod was fairly simple.

I guess this is a non-issue and will have to manually change the names of mods :) 
Thanks for the reply!
