### ISSUE TITLE
support for factorio v0.16

### ISSUE THREAD

**Issue by ekle** [Suprcheese/Logistics-Railway#8]
hi,
support for factorio 0.16 would be really cool.

i tried to simply fix the compile errors, but it doesn't seem to be enough: https://github.com/ekle/Logistics-Railway/commits/v16

**Comment by Suprcheese** [comment]
Hey,

I'm glad you're interested in this mod, but I ended support for it back when Factorio 0.13 came out, and I have no current plans to revive the mod for 0.16.

The new train [un]loading conditions introduced in the 0.13 update are completely incompatible with the way Logistics Railway functions, sadly, and I have found no way to make them compatible.
